(() => {
  const common = {
    en: {back:'All vacancies',location:'Location: Tbilisi, Vake, near Axis Towers',apply:'Send your application to @Update_Tbilisi on Telegram',about:'About UPDATE Tbilisi',company:'UPDATE Tbilisi is a wellness studio with a holistic approach to the body and quality of life. We offer massage, manual therapy, bodywork, therapeutic exercise and specialised training programmes. Our team includes 12+ certified specialists with high quality standards. We value results, innovation, personal growth and honest relationships with clients.',rating:'Rating: 4.9 on Google/Yandex, based on 200+ genuine client reviews.'},
    ka: {back:'ყველა ვაკანსია',location:'მდებარეობა: თბილისი, ვაკე, Axis Towers-ის მიმდებარედ',apply:'გამოგვიგზავნეთ განაცხადი Telegram-ში: @Update_Tbilisi',about:'UPDATE Tbilisi-ის შესახებ',company:'UPDATE Tbilisi არის wellness სტუდია, რომელიც სხეულსა და ცხოვრების ხარისხს კომპლექსურად უდგება. ვმუშაობთ მასაჟის, მანუალური თერაპიის, სხეულზე მუშაობის, სამკურნალო ფიზკულტურისა და სპეციალიზებული სავარჯიშო პროგრამების საშუალებით. ჩვენი გუნდი აერთიანებს 12-ზე მეტ სერტიფიცირებულ სპეციალისტს მაღალი ხარისხის სტანდარტებით. ვაფასებთ შედეგებს, ინოვაციას, პიროვნულ ზრდასა და კლიენტებთან გულწრფელ ურთიერთობებს.',rating:'შეფასება: 4.9 Google/Yandex-ზე, კლიენტების 200-ზე მეტი რეალური გამოხმაურების საფუძველზე.'},
  };
  const jobs = {
    'lfk-trainer': {
      en: {title:'Therapeutic Exercise Trainer',subtitle:'Join UPDATE and help clients move more freely and safely',sections:[
        ['About the role','UPDATE is looking for a therapeutic exercise trainer for one-to-one client sessions. We help people regain mobility, relieve pain and learn healthy movement. We seek someone who wants to do more than lead workouts: help clients move freely, confidently and safely, including those with pain, injuries and different functional limitations. You will work alongside our manual therapist and massage specialists.'],
        ['Requirements',['Relevant sports education; a medical qualification is an advantage.','At least one year of experience.','Knowledge of physiology, anatomy and biomechanics.','Ability to work with dysfunctions, limitations and medical conditions.','Skills in assessing and evaluating a client’s condition.','Ability to establish healthy movement patterns.','Designing individual training plans around each client’s needs and characteristics.','Experience with different age groups, from age 10 upwards.']],
        ['Responsibilities',['Deliver individual therapeutic exercise sessions.','Assess clients initially and select an appropriate programme.','Provide ongoing support and adjust the training process.','Work on movement patterns, recovery and prevention of dysfunctions.']],
        ['What we offer',['Individual work with regular clients who trust the team and value addressing root causes.','Fixed payment per completed session, paid twice a month.','Professional growth through knowledge sharing and internal team training.','Discounts on UPDATE studio services.','A friendly, results-focused team of professionals.','Official employment after successfully completing the probation period.']],
        ['How to apply',['Send your materials to @Update_Tbilisi on Telegram.','CV: a brief introduction, experience, education and specialisation.','Education documents or certificates: relevant sports, medical or continuing education.','Client cases: examples involving pain, injury recovery, dysfunctions or limitations.','Why do you want to work at UPDATE? Tell us what resonates with you in our approach and teamwork.']],
        ['Selection process',['1. Send your CV, client cases and answers via Telegram.','2. Interview: discuss your experience, education, client cases and our approach.','3. Deliver a trial training session.','4. Agree on the schedule, working format and procedures.']],
        ['Interested in this role?','Send your CV, portfolio and examples of client work. Tell us about yourself and your approach, and answer: “Why do you want to work at UPDATE Tbilisi?”'],
      ]},
      ka: {title:'სამკურნალო ფიზკულტურის მწვრთნელი',subtitle:'შემოუერთდით UPDATE-ს და დაეხმარეთ კლიენტებს უფრო თავისუფლად და უსაფრთხოდ მოძრაობაში',sections:[
        ['ვაკანსიის შესახებ','UPDATE ეძებს სამკურნალო ფიზკულტურის მწვრთნელს კლიენტებთან ინდივიდუალური მუშაობისთვის. ვეხმარებით ადამიანებს მოძრაობის აღდგენაში, ტკივილის შემცირებასა და სწორი მოძრაობის სწავლაში. ვეძებთ სპეციალისტს, რომლისთვისაც მნიშვნელოვანია არა მხოლოდ ვარჯიშის ჩატარება, არამედ ადამიანების დახმარება უფრო თავისუფალ, თავდაჯერებულ და უსაფრთხო მოძრაობაში — მათ შორის ტკივილის, ტრავმის შემდგომი მდგომარეობებისა და სხვადასხვა დისფუნქციის დროს. იმუშავებთ კომპლექსურად, მანუალურ თერაპევტთან და მასაჟის სპეციალისტებთან ერთად.'],
        ['მოთხოვნები',['პროფილური სპორტული განათლება; სამედიცინო განათლება უპირატესობაა.','მინიმუმ ერთწლიანი სამუშაო გამოცდილება.','ფიზიოლოგიის, ანატომიისა და ბიომექანიკის ცოდნა.','დისფუნქციების, შეზღუდვებისა და პათოლოგიების მქონე ადამიანებთან მუშაობის უნარი.','კლიენტის მდგომარეობის დიაგნოსტიკისა და შეფასების უნარები.','სწორი მოძრაობითი პატერნების ჩამოყალიბების უნარი.','კლიენტის საჭიროებებისა და თავისებურებების შესაბამისი ინდივიდუალური სავარჯიშო პროგრამების შედგენა.','სხვადასხვა ასაკობრივ ჯგუფთან მუშაობის გამოცდილება — 10 წლიდან ზემოთ.']],
        ['მოვალეობები',['სამკურნალო ფიზკულტურის ინდივიდუალური ვარჯიშების ჩატარება.','კლიენტის მდგომარეობის საწყისი შეფასება და შესაბამისი პროგრამის შერჩევა.','კლიენტების მუდმივი მხარდაჭერა და სავარჯიშო პროცესის კორექტირება.','მოძრაობით პატერნებზე, აღდგენასა და დარღვევების პრევენციაზე მუშაობა.']],
        ['რას გთავაზობთ',['ინდივიდუალური მუშაობა მუდმივ კლიენტებთან, რომლებიც ენდობიან გუნდს და აფასებენ პრობლემის პირველმიზეზზე მუშაობას.','ფიქსირებული ანაზღაურება ჩატარებული ვარჯიშებისთვის; გადახდა თვეში ორჯერ.','პროფესიული ზრდა, გამოცდილების გაზიარება და შიდა სწავლება მეგობრულ გუნდში.','ფასდაკლება UPDATE-ის მომსახურებებზე.','შედეგზე ორიენტირებული პროფესიონალების მეგობრული გუნდი.','გამოსაცდელი ვადის წარმატებით გავლის შემდეგ ოფიციალური დასაქმება.']],
        ['როგორ გამოგვიგზავნოთ განაცხადი',['მასალები გამოგვიგზავნეთ Telegram-ში: @Update_Tbilisi.','რეზიუმე: მოკლე ინფორმაცია თქვენ შესახებ, გამოცდილება, განათლება და სპეციალიზაცია.','განათლების დამადასტურებელი დოკუმენტები ან სერტიფიკატები — სპორტული, სამედიცინო ან დამატებითი განათლება.','კლიენტების ქეისები: ტკივილთან, ტრავმის შემდგომ აღდგენასთან, დისფუნქციებთან ან შეზღუდვებთან მუშაობის მაგალითები.','რატომ გსურთ UPDATE-ში მუშაობა? მოგვიყევით, რა არის თქვენთვის ახლობელი ჩვენს მიდგომასა და გუნდურ მუშაობაში.']],
        ['შერჩევის პროცესი',['1. რეზიუმეს, კლიენტების ქეისებისა და პასუხების გაგზავნა Telegram-ში.','2. გასაუბრება: განვიხილავთ თქვენს გამოცდილებას, განათლებას, კლიენტების ქეისებსა და ჩვენს მიდგომას.','3. საცდელი ვარჯიშის ჩატარება.','4. გრაფიკის, სამუშაო ფორმატისა და წესების შეთანხმება.']],
        ['გაინტერესებთ ვაკანსია?','გამოგვიგზავნეთ რეზიუმე, პორტფოლიო და კლიენტებთან მუშაობის მაგალითები. მოგვიყევით თქვენ შესახებ, თქვენი მიდგომის შესახებ და უპასუხეთ კითხვას: „რატომ გსურთ UPDATE Tbilisi-ში მუშაობა?“'],
      ]},
    },
    'sales-manager': {
      en: {title:'Sales Manager',subtitle:'Develop sales in two exciting fields: wellness and professional education',sections:[
        ['About the role','We are looking for a Sales Manager to develop two service areas: UPDATE Wellness Studio — massage, manual therapy, therapeutic exercise, corporate wellness programmes and retreats; and BASE for masters — a partner project providing professional education for massage therapists, trainers and coaches. You will drive growth through both new client acquisition and retention.'],
        ['Essential requirements',['Sales experience, ideally one year or more in B2B, B2C or services. Candidates without experience who want to learn and grow are also welcome.','Strong communication skills, confidence meeting new people and an ability to build rapport.','Networking and relationship-building skills.','Clear spoken and written communication.','Native-level Russian.','English at B1 (intermediate) or above.','Confident computer use, including email and messaging tools.','A desire to grow professionally.']],
        ['Nice to have',['Georgian language skills.','B2B sales experience.','Knowledge of wellness and industry trends.','Experience with CRM systems.','Skills with ChatGPT and other AI tools.']],
        ['Responsibilities: UPDATE Wellness Studio (B2B & B2C)',['Find and attract new corporate clients.','Present wellness programmes and retreats to companies.','Handle enquiries from individual clients.','Prepare commercial proposals.','Manage the client database and follow-up.']],
        ['Responsibilities: BASE for masters (B2B & B2C)',['Find organisations seeking corporate training.','Handle enquiries from prospective course participants.','Advise clients on educational programmes.','Build a database of professionals in target niches.','Manage the sales pipeline in CRM.']],
        ['Shared responsibilities',['Meet KPIs for contracts and sales.','Advise clients in Russian and English.','Report on activity and results.','Work with the team to improve the sales process.']],
        ['About the companies','UPDATE has 12+ certified specialists and an established base of corporate IT clients in Georgia. BASE for masters is an educational platform developed with a partner. Courses are taught by practising professionals with 10–15+ years of experience, in person in Tbilisi and online.'],
        ['What we offer',['Base salary plus sales commission; income depends on your results.','Discounts on all UPDATE services for you and your family.','Full product training for UPDATE and BASE for masters.','Mentoring and onboarding from an experienced sales leader.','Remote or office work with an individually agreed schedule.','Growth towards team leader or sales director roles.','CRM, a knowledge base, proposal templates and presentation materials.','A team of committed professionals.']],
        ['Working conditions','Base salary plus commission. Salary details are agreed individually after the interview, with a transparent commission system. Choose remote or office work, agree a flexible schedule and potentially combine the role with other activities.'],
        ['How to apply',['Send your materials to @Update_Tbilisi on Telegram.','CV: a brief introduction, experience and skills.','An example of a successful deal, if you have sales experience.','If you are new to sales: why do you believe you can succeed? Tell us why you are confident and want to learn.','Why do you want to work at UPDATE? Tell us what attracts you to the company and its work.']],
        ['Selection process',['1. Send your CV, deal example and answers via Telegram.','2. Interview: discuss your experience, deals and understanding of our services.','3. Product training and internship: 3–5 days depending on your level.','4. Agree on the schedule and working format, then begin independent work.']],
        ['Ready to join the team?','Send your materials and we will start a conversation about working together.'],
      ]},
      ka: {title:'გაყიდვების მენეჯერი',subtitle:'განავითარეთ გაყიდვები ორ საინტერესო სფეროში: wellness და პროფესიული განათლება',sections:[
        ['ვაკანსიის შესახებ','ვეძებთ გაყიდვების მენეჯერს ორი მიმართულების განვითარებისთვის: UPDATE Wellness Studio — მასაჟი, მანუალური თერაპია, სამკურნალო ფიზკულტურა, კორპორაციული wellness პროგრამები და რეტრიტები; და BASE for masters — პარტნიორული პროექტი, რომელიც მასაჟის სპეციალისტებს, მწვრთნელებსა და ქოუჩებს პროფესიულ განათლებას სთავაზობს. თქვენი ამოცანა იქნება ზრდის ხელშეწყობა როგორც ახალი კლიენტების მოზიდვით, ისე არსებულების შენარჩუნებით.'],
        ['აუცილებელი მოთხოვნები',['გაყიდვების გამოცდილება — სასურველია მინიმუმ ერთი წელი B2B, B2C ან მომსახურების სფეროში. გამოცდილების არმქონე კანდიდატებსაც მივესალმებით, თუ სურთ სწავლა და განვითარება.','კომუნიკაბელურობა, ახალ ადამიანებთან თავისუფლად ურთიერთობა და საერთო ენის გამონახვის უნარი.','ნეთვორქინგისა და ურთიერთობების განვითარების უნარები.','გამართული ზეპირი და წერილობითი მეტყველება.','რუსული ენა მშობლიური ენის დონეზე.','ინგლისური მინიმუმ B1 (საშუალო) დონეზე.','კომპიუტერის, ელფოსტისა და მესენჯერების თავდაჯერებული გამოყენება.','პროფესიული ზრდისა და განვითარების სურვილი.']],
        ['სასურველი უპირატესობები',['ქართული ენის ცოდნა.','B2B გაყიდვების გამოცდილება.','wellness სფეროსა და ტენდენციების ცოდნა.','CRM სისტემებთან მუშაობის გამოცდილება.','ChatGPT-ისა და სხვა AI ინსტრუმენტების გამოყენების უნარები.']],
        ['მოვალეობები: UPDATE Wellness Studio (B2B & B2C)',['ახალი კორპორაციული კლიენტების მოძიება და მოზიდვა.','კომპანიებისთვის wellness პროგრამებისა და რეტრიტების წარდგენა.','ინდივიდუალური კლიენტების შემოსული მოთხოვნების დამუშავება.','კომერციული შეთავაზებების მომზადება.','კლიენტების ბაზის მართვა და შემდგომი კომუნიკაცია.']],
        ['მოვალეობები: BASE for masters (B2B & B2C)',['ორგანიზაციების მოძიება, რომლებსაც კორპორაციული სწავლება სჭირდებათ.','პოტენციური მსმენელების მოთხოვნების დამუშავება.','საგანმანათლებლო პროგრამებზე კონსულტირება.','სამიზნე მიმართულებების სპეციალისტების ბაზის შექმნა.','CRM-ში გაყიდვების პროცესის მართვა.']],
        ['საერთო მოვალეობები',['ხელშეკრულებებისა და გაყიდვების რაოდენობრივი KPI-ების მიღწევა.','კლიენტების კონსულტირება რუსულ და ინგლისურ ენებზე.','აქტივობებისა და შედეგების ანგარიშების მომზადება.','გუნდთან თანამშრომლობა გაყიდვების პროცესის გასაუმჯობესებლად.']],
        ['კომპანიების შესახებ','UPDATE აერთიანებს 12-ზე მეტ სერტიფიცირებულ სპეციალისტს და საქართველოში IT სფეროს კორპორაციული კლიენტების მყარ ბაზას ფლობს. BASE for masters პარტნიორთან ერთად შექმნილი საგანმანათლებლო პლატფორმაა. კურსებს უძღვებიან პრაქტიკოსი სპეციალისტები 10–15 წელზე მეტი გამოცდილებით. სწავლება მიმდინარეობს თბილისში პირისპირ და ონლაინ.'],
        ['რას გთავაზობთ',['ფიქსირებული ხელფასი და გაყიდვების პროცენტი; შემოსავალი დამოკიდებულია შედეგებზე.','ფასდაკლებები UPDATE-ის ყველა მომსახურებაზე თქვენთვის და თქვენი ოჯახისთვის.','სრული სწავლება UPDATE-ისა და BASE for masters-ის პროდუქტებზე.','გამოცდილი გაყიდვების ლიდერის მენტორობა და სამუშაოში ინტეგრაცია.','დისტანციური ან ოფისიდან მუშაობა ინდივიდუალურად შეთანხმებული გრაფიკით.','გუნდის ლიდერად ან გაყიდვების დირექტორად განვითარების შესაძლებლობა.','CRM, ცოდნის ბაზა, კომერციული შეთავაზებების შაბლონები და საპრეზენტაციო მასალები.','საქმის ერთგული პროფესიონალების გუნდი.']],
        ['სამუშაო პირობები','ფიქსირებული ხელფასი და გაყიდვების პროცენტი. დეტალები ინდივიდუალურად განიხილება გასაუბრების შემდეგ. პროცენტის დარიცხვის სისტემა გამჭვირვალეა. შეგიძლიათ აირჩიოთ დისტანციური ან ოფისიდან მუშაობა, შეათანხმოთ მოქნილი გრაფიკი და შეუთავსოთ სამუშაო სხვა საქმიანობას.'],
        ['როგორ გამოგვიგზავნოთ განაცხადი',['მასალები გამოგვიგზავნეთ Telegram-ში: @Update_Tbilisi.','რეზიუმე: მოკლე ინფორმაცია თქვენ შესახებ, გამოცდილება და კომპეტენციები.','წარმატებული გარიგების მაგალითი, თუ გაყიდვების გამოცდილება გაქვთ.','თუ გაყიდვებში ახალი ხართ: რატომ ფიქრობთ, რომ წარმატებას მიაღწევთ? ახსენით, რატომ გჯერათ საკუთარი თავის და გსურთ სწავლა.','რატომ გსურთ UPDATE-ში მუშაობა? მოგვიყევით, რა გიზიდავთ კომპანიასა და მის მიმართულებებში.']],
        ['შერჩევის პროცესი',['1. რეზიუმეს, გარიგების მაგალითისა და პასუხების გაგზავნა Telegram-ში.','2. გასაუბრება: განვიხილავთ გამოცდილებას, გარიგებებსა და ჩვენი მომსახურებების გაგებას.','3. პროდუქტების სწავლება და სტაჟირება — 3–5 დღე, თქვენი დონის მიხედვით.','4. გრაფიკისა და სამუშაო ფორმატის შეთანხმება და დამოუკიდებელი მუშაობის დაწყება.']],
        ['მზად ხართ გუნდში შემოსაერთებლად?','გამოგვიგზავნეთ თქვენი მასალები და დავიწყოთ საუბარი თანამშრომლობაზე.'],
      ]},
    },
  };
  const slug=location.pathname.split('/').filter(Boolean).pop();
  if(!jobs[slug]) return;
  const container=document.querySelector('.container'), title=document.querySelector('h1'), subtitle=document.querySelector('.subtitle'), locationLine=document.querySelector('.location');
  const original={content:container.innerHTML,title:title.textContent,subtitle:subtitle.textContent,location:locationLine.textContent,documentTitle:document.title};
  const nav=document.createElement('nav'); nav.setAttribute('aria-label','Language'); nav.style.cssText='display:flex;gap:12px;justify-content:center;flex-wrap:wrap;padding:16px;background:#171813;color:white';
  const back=document.createElement('a');back.style.cssText='color:inherit;padding:10px';nav.append(back);
  const buttons=['ru','en','ka'].map(l=>{const b=document.createElement('button');b.textContent=l.toUpperCase();b.style.cssText='font:inherit;cursor:pointer;padding:10px 14px;border:1px solid #999;background:transparent;color:inherit';b.onclick=()=>{const u=new URL(location.href);u.searchParams.set('lang',l);history.replaceState(null,'',u);render(l);};nav.append(b);return b;});
  document.body.prepend(nav);
  function render(l){
    if(!['en','ka'].includes(l))l='ru';
    document.documentElement.lang=l;back.textContent=l==='ru'?'Все вакансии':common[l].back;back.href='/vacancies/?lang='+l;
    buttons.forEach((b,i)=>{const active=['ru','en','ka'][i]===l;b.setAttribute('aria-pressed',String(active));b.style.background=active?'#ff6b1a':'transparent';});
    document.querySelectorAll('a[href="https://update-club.com"]').forEach(a=>a.href='https://update-club.com/?lang='+l);
    if(l==='ru'){container.innerHTML=original.content;title.textContent=original.title;subtitle.textContent=original.subtitle;locationLine.textContent=original.location;document.title=original.documentTitle;return;}
    const data=jobs[slug][l],c=common[l];title.textContent=data.title;subtitle.textContent=data.subtitle;locationLine.textContent=c.location;document.title=data.title+' — UPDATE Tbilisi';
    container.replaceChildren();
    const sections=[...data.sections];sections.splice(slug==='lfk-trainer'?3:7,0,[c.about,c.company+' '+c.rating]);
    for(const [heading,body] of sections){const section=document.createElement('section'),h=document.createElement('h2');h.textContent=heading;section.append(h);if(Array.isArray(body)){const ul=document.createElement('ul');for(const item of body){const li=document.createElement('li');li.textContent=item;ul.append(li);}section.append(ul);}else{const para=document.createElement('p');para.textContent=body;section.append(para);}container.append(section);}
    const section=document.createElement('section');section.className='cta-section';const a=document.createElement('a');a.className='telegram-link';a.href='https://t.me/Update_Tbilisi';a.textContent=c.apply;section.append(a);container.append(section);
  }
  const restore=()=>render(new URLSearchParams(location.search).get('lang'));
  window.addEventListener('popstate',restore);restore();
})();
